# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SSETest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SSETest
  pod 'IKEventSource'
  pod 'LDSwiftEventSource', '~> 1.3'
end
